baseURL = 'https://bristolgophers.dev/'
languageCode = 'en-gb'
title = 'Bristol Gophers'
theme = "PaperMod"

[params.profileMode]
enabled = true
title = "Bristol Gophers"
# subtitle = "This is subtitle"
# imageUrl = "<image link>"
# imageTitle = "<title of image as alt>"
# imageWidth = 120
# imageHeight = 120

# [[params.profileMode.buttons]]
# name = "Apply"
# url = "apply"

# [[params.profileMode.buttons]]
# name = "Sponsors"
# url = "sponsors"

[[params.profileMode.buttons]]
name = "Code Of Conduct"
url = "https://go.dev/conduct"

[[params.profileMode.buttons]]
name = "Meetup"
url = "https://www.meetup.com/golang-bristol/"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/golangbristol"

[[params.socialIcons]]
name = "github"
url = "https://github.com/bristolgolang"
